# Generated by Django 4.2.3 on 2023-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='gst',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='igst',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
