# Generated by Django 4.2.3 on 2023-12-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillApp', '0002_items_gst_items_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='cgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='igst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='sgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='state_of_supply',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='cgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='igst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='state_of_supply',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
