# Generated by Django 4.2.3 on 2024-08-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillApp', '0002_alter_clienttrials_company_alter_clienttrials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
